### ISSUE TITLE
API Token leaked

### ISSUE THREAD

**Issue by das7pad** [jjjbushjjj/telegram_fun_bot#1]
The token should remain private ;)

Please revert it asap.

https://github.com/jjjbushjjj/telegram_fun_bot/blob/9972c407ff4023f3b94462d8758fa370ff56e343/bot_api.token#L3

**Comment by jjjbushjjj** [comment]
yes i know :) Bot is currently do nothing special. So it isn't problem atm.

**Comment by das7pad** [comment]
:+1:  for https://github.com/jjjbushjjj/telegram_fun_bot/commit/6b71540e57be3938f3488c92fd079c2a72acc563
